### ISSUE TITLE
Parser fails to read attribute without quotes

### ISSUE THREAD

**Issue by aolde** [simplyio/shortcoder#2]
Content: 
    [pagelist root=docs descendants=false]

Root = "docs descendants=false"

**Comment by aolde** [comment]
This is fixed.

**Comment by adigourdi** [comment]
Hello, apparently this is not fixed, just tried it (with current release 0.3.0), and it doesn't work without quotes

All the listed attributes get appended into the first one

Eg
```
[code arg1=val1 arg2=val2 arg3=val3]
```

Returns
```
arg1 => "val1 arg2=val2 arg3=val3"
arg2 => empty
arg3 => empty
```
